/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Vilad (https://sketchfab.com/Vilad)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/marble-shelf-2-0c48aa1f33da4831b9fc991fdacdd08f
title: Marble Shelf 2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Shelf(props) {
  const { nodes, materials } = useGLTF('/marble_shelf/scene.gltf')
  return (
    <group  {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
          <group position={[331.58, 50.82, 74.18]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Marble_Shelf_2_Material002_0.geometry} material={materials['Material.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/marble_shelf/scene.gltf')
